### ISSUE TITLE
Current status od federation

### ISSUE THREAD

**Issue by george-oakling** [kubernetes/federation#227] opened 2018-02-12 16:07 UTC
1. As noted by https://github.com/kubernetes/federation/issues/226 the current version is not packaged to standardn K8s distribution.

2. If you install it by snap, you get the redirect error right after running the command (with or without params). 

3. If you download it manually from https://storage.googleapis.com/kubernetes-release/release/v1.8.7/kubernetes-client-linux-amd64.tar.gz and unpack and run it in accordance to the whole process, you end up with Error from server (Forbidden): roles.rbac.authorization.k8s.io "federation-system:federation-controller-manager" is forbidden: attempt to grant extra privileges.

My question is therefore: what is the current status of Kubernetes federation? Should we consider trying it? Are there any public plans that could be shared with us? I couldnt find any info on that, and as it is part of the official Kubernetes Github project, I was expecting a little bit more :)

I will send some PRs to documentation to update the download link and issue a bug in snap package.

**Comment by irfanurrehman** [comment] 2018-02-12 17:16
@george-oakling, federation project lives.. :-). You probably did hit an offbeat situation as already talked about in #110. A simple solution would probably be to use the workaround listed in that issue.
Also, since 1.9.0 we moved out of core kubernetes, and thus the latest releases do not contain federation binaries. We did hit some hiccups in providing alternative location for those binaries, but the release process is now ironed out and you should get an update both about the release and updated documentation within few days.

**Comment by george-oakling** [comment] 2018-02-13 11:33
Okay, thank you :)

**Comment by irfanurrehman** [comment] 2018-02-16 15:44
@george-oakling 
Release published [here](https://github.com/kubernetes/federation/releases/tag/v1.9.0-alpha.3)

**Comment by george-oakling** [comment] 2018-02-19 18:35
Hi! Thanks, I am getting "error: no configuration has been provided." when trying to `./kubefed init kfed \
    --host-cluster-context=prod-eu \
    --dns-zone-name="xxx.network." \
    --dns-provider="google-clouddns"`

**Comment by george-oakling** [comment] 2018-02-19 21:52
Sorry, my mistake, it works...

**Comment by george-oakling** [comment] 2018-02-19 22:58
I add
```
gcloud config set container/use_client_certificate True
export CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True
```

But it ends up again at 
```
Error from server (Forbidden): roles.rbac.authorization.k8s.io "federation-system:federation-controller-manager" is forbidden: attempt to grant extra privileges: [PolicyRule{Resourcthe es:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]}] user=&{client  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```
so I tried to add the rolebinding:
```
kubectl create rolebinding \
    --clusterrole=admin \
    --namespace=federation-system \
    --serviceaccount=federation-system:federation-controller-manager \
    federation-system:federation-controller-manager
```
but still - it doesn't work... do you know what could be the reason @irfanurrehman 

Thanks in advance.

**Comment by george-oakling** [comment] 2018-02-20 12:24
And also getting the same error on 1.8.7 GKE and 1.9.2 GKE

**Comment by irfanurrehman** [comment] 2018-02-23 15:14
@george-oakling 
- the federation binaries are available as per the [release notes](https://github.com/kubernetes/federation/releases/tag/v1.9.0-alpha.3).
- the documentation now reflects how to get kubefed correctly as per [this PR](https://github.com/kubernetes/website/pull/7429).
- the RBAC issue is an open issue with the latest version k8s clusters but federation functions with the workaround as confirmed by you [here](https://github.com/kubernetes/federation/issues/110#issuecomment-367648851).

Please let me know if this issue can be marked as closed.

**Comment by irfanurrehman** [comment] 2018-02-27 17:26
@fkorotkov we have changed the location for the fcp image release, which reflects in the latest [release notes](https://github.com/kubernetes/federation/releases/tag/v1.9.0-alpha.3).
The same is also updated as the default in the latest kubefed code.
Its is `gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:latest`. 
Please let me know if and why this might not be ok.

**Comment by fkorotkov** [comment] 2018-02-27 17:39
I see. I was confused by `jkns` suffix. Like it's some kind of Jenkins artifact not related to the release.

**Comment by irfanurrehman** [comment] 2018-02-27 17:55
@george-oakling closing this issue as resolved, please feel free to reopen if you think otherwise.
/close

**Closed by irfanurrehman** 2018-02-27 17:56 UTC

**Comment by fkorotkov** [comment] 2018-07-19 15:47
@irfanurrehman do you know if there are any plans to release a new version of federation? The last release was in February 😅
